### ISSUE TITLE
Make the connection button resolve stark domains and PFPs

### ISSUE THREAD

**Issue by fricoben** [starknet-id/affiliate.starknet.id#24] opened 2024-11-15 03:12 UTC
## Description 📹

Our top right-corner button is not showing .stark domains and PFPs. We need to make it so so it looks like so

<img width="600" alt="Capture d’écran 2024-11-15 à 09 55 13" src="https://github.com/user-attachments/assets/cf366ab3-975d-43dd-bdcc-fc5310598c82">

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
  - [ ] Refactor the button component to make it resolve stark domains and PFPs using this [button component](https://github.com/lfglabs-dev/app.starknet.id/blob/testnet/components/UI/connectButton.tsx) as model
  - [ ] Make it work taking example from  in [this context](https://github.com/lfglabs-dev/app.starknet.id/blob/25f533b385da3e1a4024c24643119802ef1a2e24/components/UI/navbar.tsx#L171)

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by wheval** [comment] 2024-11-22 06:11
Hello @fricoben, I can get this done. 
I have worked on something similar here https://github.com/lfglabs-dev/starknet.quest/pull/939.
Please assign. Thank you.

ETA is 1 day.

**Comment by 0xdevcollins** [comment] 2024-11-22 07:14
Could I take a shot at this?

**Comment by mimisavage** [comment] 2024-11-22 07:30
Could I take on this issue?

**Comment by petersdt** [comment] 2024-11-22 07:54
@fricoben May I be assigned to this?

ETA <= 48hrs

**Comment by mayasimi** [comment] 2024-11-22 07:56
Can I be assigned to this?

**Comment by NueloSE** [comment] 2024-11-22 08:03
May I take care of this?

**Comment by suhas-sensei** [comment] 2024-11-22 10:38
Mind if I try this one? I will do the requested changes in 36 hours.

**Comment by Jagadeeshftw** [comment] 2024-11-22 18:00
Hi @fricoben,

I want to take up this issue as I have experience with front-end development and can resolve it efficiently. I’ll ensure the button resolves Stark domains and PFPs as described and will raise a PR within the next 12 hours. Could you please assign this issue to me?

**Comment by Supa-mega** [comment] 2024-11-29 14:31
please 🙏 I’d love to work on this task.

**Comment by 0xDeon** [comment] 2024-11-29 16:29
I’d like to resolve this.

I can have this delivered in less than 48 hrs and will like to take this issue

**Comment by Psalmuel01** [comment] 2024-11-29 22:33
Can I try solving this issue?

**Comment by JoshdfG** [comment] 2024-11-30 01:01
Can I work on this, please?

**Comment by Marchand-Nicolas** [comment] 2024-12-06 08:12
Hello, everything good @NueloSE ?

**Comment by NueloSE** [comment] 2024-12-06 15:19
@Marchand-Nicolas 

I have done the required task and added a default profile picture incase there isn't anyone from the user's account but the issue is that the domain is showing the user address instead of the user's domain, i even tried buying a domain still nothing is changing.
Then i tried logging out the domain to see if it is actually getting the  user's domain it is showing undefined on the console
i even tried following the reference you gave but still nothing
Do you know or have any idea on what i can do to resolve it or is there something i'm missing 🤔

**Comment by Marchand-Nicolas** [comment] 2024-12-06 15:58
> @Marchand-Nicolas
> 
> I have done the required task and added a default profile picture incase there isn't anyone from the user's account but the issue is that the domain is showing the user address instead of the user's domain, i even tried buying a domain still nothing is changing. Then i tried logging out the domain to see if it is actually getting the user's domain it is showing undefined on the console i even tried following the reference you gave but still nothing Do you know or have any idea on what i can do to resolve it or is there something i'm missing 🤔

Make sure your env variables are fine, especially:
NEXT_PUBLIC_RPC_URL=https://rpc.starknet.id
and the contracts (here are the addresses: https://www.notion.so/lfg-labs/Deployed-Contracts-ee3370b1d20c45b59bb5157ce7f4e017)

**Closed as completed** 2024-12-21 10:01 UTC
Labels: Open for contribution, ODHack13, Expert issue
